version: "3.3"

services:
  sdnr:
    image: openbackhaul/mwdomaincontroller:v5.0.6-SR19
    container_name: sdnr
    ports:
      - "8181:8181"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=120
      - odl-snapshots:${ODL_HOME}/snapshots
      - odl-segmented-journal:${ODL_HOME}/segmented-journal
      - odl-cache:${ODL_HOME}/cache
    # uncomment volumes section to stores logs in host folder /var/tmp/mwdomaincontroller/logs
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

volumes:
      #- /var/tmp/mwdomaincontroller/logs:/opt/opendaylight/data/log
    odl-snapshots:
    odl-segmented-journal:
    odl-cache:
